### PR TITLE
feat: switch to tsconfigRaw

### LINKED ISSUE #83: esbuild-register does not respect jsxImportSource in tsconfig.json
See https://esbuild.github.io/api/#jsx-import-source

### PR DESCRIPTION
**Pull request by shigma**
fix #83

### CODE REVIEW

**Comment by pspeter3** [comment]
This seems extremely useful for respecting tsconfig settings. Any chance this can get merged?

**Comment by shigma** [comment]
> This seems extremely useful for respecting tsconfig settings. Any chance this can get merged?

I've made a fork for my personal use: [@shigma/esbuild-register](https://www.npmjs.com/package/@shigma/esbuild-register).

**Comment by pauleveritt** [comment]
I hate doing a post that says "I agree" but...I agree.

**Pull request merged**
