### PR TITLE
Update tsconfig-paths

### PR DESCRIPTION
**Pull request by Karibash**
close: #85

### CODE REVIEW

**Comment by psychobolt** [comment]
This is needed to support TypeScript 5.0 for Storybook. https://github.com/storybookjs/storybook/issues/21792

**Comment by naporin0624** [comment]
I ran into this problem in TS 5.0 when I used extends as an array. This fix is very important. I look forward to seeing it merged.

I have created a patch file that can be used with patch-package to address this issue.
https://gist.github.com/naporin0624/70c2e00f791d881895910a8f2cdb3026

**Comment by bastiankistner** [comment]
would be great if this could be merged! was just running into the `extends` is an array issue, which is a very helpful typescript feature

**Comment by adonaicandido** [comment]
Waiting on this as well. Storybook with TS 5.0 and Sveltekit depends on this.

**Comment by CloudBranch** [comment]
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received an instance of Array

**Comment by lagunovsky** [comment]
[As of March 2023, a good way to eliminate the NodeJS relative paths is to use the imports property in package.json. (In the codes below, #root is the project root.)](https://stackoverflow.com/a/75817914)

```js
// package.json
{
  "imports": {
    "#root/*.js": "./*.js"
  }
}

// main.js:
const Source = require('#root/path/to/Source.js');

// Source.js:
module.exports = class Source {
  // ...
}
```

**Comment by prisis** [comment]
Hey @egoist , do you have some time to take a look on this issue?

**Comment by anneau** [comment]
Please merge this.

**Comment by ndelangen** [comment]
@egoist would you be able to look at merging this perhaps?

Storybook needs this to support newer TS5 features, see: https://github.com/storybookjs/storybook/issues/21792

🙏🙏🙏

**Comment by unknownproperty** [comment]
+1 for storybook support

**Comment by prisis** [comment]
Thank you @egoist  ❤️

**Pull request merged**
